AiryPreprocess:
  enable_box_filter: true
  filter_target_frame: "base_link"
  filter_box_min_x: -0.4
  filter_box_max_x: 0.4
  filter_box_min_y: -0.4
  filter_box_max_y: 0.4
  filter_box_min_z: -0.5
  filter_box_max_z: 0.5
  lidar_blind_zone: 0.05
  min_reflectivity: 20
  max_reflectivity: 112